/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROODSIGMADM
#define ROODSIGMADM

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooDsigmadm : public RooAbsPdf {
public:
  RooDsigmadm() {} ; 
  RooDsigmadm(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _p1,
	      RooAbsReal& _p2,
	      RooAbsReal& _p3);
  RooDsigmadm(const RooDsigmadm& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooDsigmadm(*this,newname); }
  inline virtual ~RooDsigmadm() { }

protected:

  RooRealProxy x ;
  RooRealProxy p1 ;
  RooRealProxy p2 ;
  RooRealProxy p3 ;
  
  Double_t evaluate() const ;
private:

  ClassDef(RooDsigmadm,1) // Your description goes here...
};
 
#endif
